"""Data model for purity analysis."""

from library_analyzer.processing.api.purity_analysis.model._purity import (  # TODO: rework this
    Expression,
    FileRead,
    FileWrite,
    ImpurityReason,
    ParameterAccess,
    StringLiteral,
    NonLocalVariableRead,
    NonLocalVariableWrite,
    PurityResult,
    Impure,
    Pure,
)
from library_analyzer.processing.api.purity_analysis.model._reference import (
    ReferenceNode,
)
from library_analyzer.processing.api.purity_analysis.model._scope import (
    Builtin,
    ClassScope,
    FunctionScope,
    FunctionReference,
    ClassVariable,
    GlobalVariable,
    Import,
    InstanceVariable,
    LocalVariable,
    MemberAccess,
    MemberAccessTarget,
    MemberAccessValue,
    ModuleData,
    NodeID,
    Parameter,
    Scope,
    Symbol,
)

__all__ = [
    "ModuleData",
    "Scope",
    "ClassScope",
    "FunctionScope",
    "FunctionReference",
    "MemberAccess",
    "MemberAccessTarget",
    "MemberAccessValue",
    "NodeID",
    "Symbol",
    "Parameter",
    "LocalVariable",
    "GlobalVariable",
    "ClassVariable",
    "InstanceVariable",
    "Import",
    "Builtin",
    "ReferenceNode",
    "Expression",
    "ParameterAccess",
    "StringLiteral",
    "ImpurityReason",
    "NonLocalVariableRead",
    "NonLocalVariableWrite",
    "FileRead",
    "FileWrite",
    "PurityResult",
    "Pure",
    "Impure",
]
